### ISSUE TITLE
Installation does not work (heroku/8.0.2)

### ISSUE THREAD

**Issue by LeipeLeon** [heroku/heroku-repo#124]
Trying to install throws the following error:

```shell
$ heroku version
heroku/8.0.2 darwin-x64 node-v16.19.0

$ heroku plugins:install heroku-repo
warning "@heroku-cli/plugin-addons-admin > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin heroku-repo... failed
 ›   Error: plugin is invalid
```

**Comment by visnup** [comment]
Same for me. Can confirm that downgrading Heroku CLI to `heroku/7.68.2 darwin-x64 node-v14.19.0` ended up working.

**Comment by thehon** [comment]
Opposite for me - I upgraded to `heroku/8.1.4 darwin-x64 node-v16.19.0` and I was able to install herok-repov 1.0.14

**Comment by LeipeLeon** [comment]
confirmed. https://github.com/heroku/cli/pull/2328 probably fixed it.
