### ISSUE TITLE
repo:purge_cache error

### ISSUE THREAD

**Issue by jeanadrien** [heroku/heroku-repo#14]
Hello I'm trying to use your plugin in order to purge ivy cache prior to push a new version of my application via git.

Running the command

$ heroku repo:purge_cache -a <my app>

I have the following result 

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined local variable or method `releases' for #<Heroku::Command::Repo:0x00000100b45f68> (NameError)
    Backtrace:   /Users/jeanvaucher/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:80:in `cache_delete_url'
                 /Users/jeanvaucher/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:22:in `purge_cache'
                 /Users/jeanvaucher/.heroku/client/lib/heroku/command.rb:213:in `run'
                 /Users/jeanvaucher/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/local/heroku/bin/heroku:24:in `<main>'

    Command:     heroku repo:purge_cache -a <my app>
    Plugins:     heroku-repo
    Version:     heroku-toolbelt/3.0.1 (x86_64-darwin10.8.0) ruby/1.9.3

Do I miss something ?
I just installed the plugin with

$ heroku plugins:install https://github.com/lstoll/heroku-repo.git

Nothing special. I tried this, in replacement of the cleancache branch of the sbt scala buildpack

Any clue appreciated.
My best

-- Jean Vaucher

**Comment by jacebrowning** [comment]
I am also having a problem with this command:

```
Error:       undefined method `index' for #<Heroku::Command::Run:0x007fb323dd21c8> (NoMethodError)
Command:     heroku repo:purge_cache -a <my app>
Plugins:     heroku-repo
Version:     heroku-toolbelt/3.42.9 (x86_64-darwin14.0) ruby/2.1.4
Error ID:    d6c3fd455cb64fcfbac5d26d1eea09b9
```

**Comment by whatthewhat** [comment]
Also getting `undefined method 'index'`, here is the stack trace from the log:

```
Heroku client internal error.
undefined method `index' for #<Heroku::Command::Run:0x0000010213b610>
/Users/whatthewhat/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:139:in `run'
/Users/whatthewhat/.heroku/plugins/heroku-repo/lib/heroku/command/repo.rb:37:in `purge_cache'
/Users/whatthewhat/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/whatthewhat/.heroku/client/lib/heroku/cli.rb:29:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

**Comment by dickeyxxx** [comment]
can you update the plugin and try again? just pushed out a fix

**Comment by whatthewhat** [comment]
@dickeyxxx all good after updating, thanks! :+1:

**Comment by jacebrowning** [comment]
:+1:

**Comment by esauter5** [comment]
:+1:

**Comment by mrodrigues** [comment]
:+1:
