### ISSUE TITLE
repo:rebuild does not work w/ two apps in the same repo

### ISSUE THREAD

**Issue by kennknowles** [heroku/heroku-repo#16]
`heroku repo:rebuild` cannot read my application's remote from my git config because there are two applications with different remotes (`production` and `staging`)

So it defaults to a remote named `heroku` which does not exist.

Suggested behavior:
1. Figure out the remote some other way, like from the `--app` parameter. I don't know much about Heroku plugins so I don't know if this is possible.
2. Add a flag `--remote` that the user must pass. If they do not, then print a useful message and `exit 1`.

I'm not that picky about my own configuration, if you have any suggestions.

**Comment by jkwatson** [comment]
It would be really great if this didn't require a workaround.  I'm in this position, as well, as we have both the stage & production remotes, named as such, and neither remote is named 'heroku'.

**Comment by csphere** [comment]
Would love a patch.

Just need the ability to pass in an -r option for what the remote is named and inject it on line 108 of https://github.com/heroku/heroku-repo/blob/master/lib/heroku/command/repo.rb

**Comment by jkwatson** [comment]
Is there a way to have it also respect the standard heroku `--remote xyz` method of selecting a heroku app?  I don't know much about how these plugins work at all.
