### ISSUE TITLE
Commands assume git master branch

### ISSUE THREAD

**Issue by adamlwgriffiths** [heroku/heroku-repo#22]
All git commands assume `master` branch.
`"git push #{extract_app_from_git_config || "heroku"} master"`

Git branches are the best way to manage various deployment environments (staging, production). This is done by specifying the local branch to push from
`git push <remote> <branch>:master`

Hardcoding this to `master` prevents the majority of users from using this tool for any git related commands.

**Comment by ses4j** [comment]
:+1:
