### ISSUE TITLE
repo:purge_cache when there is nothing to purge

### ISSUE THREAD

**Issue by cyx** [heroku/heroku-repo#36]
If for some reason the cache_get_url results in a 404 (maybe due to an old version of the plugin being used), we get a cryptic error when running the command.

Perhaps we can just silently fail / run without showing any errors for cases like this.

**Comment by edmorley** [comment]
This is fixed in the new `builds:cache:purge` command added to [heroku-builds](https://github.com/heroku/heroku-builds) that is replacing the `repo:purge_cache` command in this repo (see #77):

```
treeherder $ ths builds:cache:purge
Purging build cache for treeherder-stage... done
treeherder $ ths builds:cache:purge
Purging build cache for treeherder-stage... done
```

As such, I think this can now be closed.

**Comment by dmathieu** [comment]
Thank you @edmorley

**Comment by econner** [comment]
Ah yes, the old replace a command 2 years ago and never update `heroku-repo`

**Comment by econner** [comment]
Hello from 2019. Are we not supposed to be using the purge_cache command in heroku repo? As of 2017 it was going to be replaced?
