### ISSUE TITLE
`repo` is not a heroku command

### ISSUE THREAD

**Issue by timscott** [heroku/heroku-repo#40]
```bash
> heroku plugins:install https://github.com/heroku/heroku-repo.git
Installing https://github.com/heroku/heroku-repo.git... done

> heroku repo
 !    `repo` is not a heroku command.
```

I tried ```heroku restart```. I have version 3.38.3 of heroku toolbelt.

**Comment by tt** [comment]
The error message is correct; the plug-in doesn't export a "repo" command:

    % heroku help repo
    Additional commands, type "heroku help COMMAND" for more details:
    
      repo:clone        #  Sets the bare repo for immediate consumption
      repo:download     #  Download the repository
      repo:gc           #  Run a git gc --agressive on the applications repository
      repo:purge-cache  #  Deletes the contents the build cache in the repository
      repo:reset        #  Reset the repo

What are you trying to do?

**Comment by murtazapithawala** [comment]
try
heroku plugins:install heroku-repo
to install correctly
