### ISSUE TITLE
purge-cache fails

### ISSUE THREAD

**Issue by josiahsprague** [heroku/heroku-repo#48]
Any time I try to run `heroku repo:purge-cache -a myappname` it fails with;

```
~/tmp/repo_tmp/unpack $ tar -zxf ../repo-cache.tgz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I'm trying to purge the build cache of a review app in the process of debugging a buildpack related issue.

**Comment by tt** [comment]
This happens when there is no build cache. (It's a terrible error message, though, and we should fix that.)

Did the build fail? The build cache is only written on successful builds.

**Comment by josiahsprague** [comment]
Yeah, the build failed because of an issue with the buildpack I was using. I was actually trying to use `purge-cache` to resolve the issue because I thought my issue was cache related. Turns out I had a broken `npm-shrinkwrap.json`, so this issue isn't relevant to me anymore. Feel free to leave it open if you want to investigate further.
