### ISSUE TITLE
Heroku repo commands hang

### ISSUE THREAD

**Issue by Tonkpils** [heroku/heroku-repo#50]
Running the `heroku repo:gc` or `heroku repo:purge_cache` commands hang even though the app's logs  show the process exited with a status 0 and state changed from up to complete.

This was working fine yesterday but today they just seem to get stuck on the terminal until I cancel it. It seems the commands do end up executing but the CLI doesn't return back control.

**Comment by tt** [comment]
@dickeyxxx, did anything change for `heroku run`?

**Comment by dickeyxxx** [comment]
actually yes, I'll look into it

**Comment by dickeyxxx** [comment]
This should be resolved in v5.2.6

**Comment by Tonkpils** [comment]
@dickeyxxx this is happening again
