### ISSUE TITLE
ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000 when trying heroku repo:purge_cache -a appName 

### ISSUE THREAD

**Issue by ilmoralito** [heroku/heroku-repo#51]
I am getting ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000 when tring heroku repo:purge_cache -a appName i get the same message if i try heroku repo:reset -a appname

**Comment by dmathieu** [comment]
Is your company firewall blocking port 5000? Does `heroku run bash` work?

**Comment by ilmoralito** [comment]
5000 port was blocked. Its working now. Thanks for answering!

**Comment by dmathieu** [comment]
You're welcome.

**Comment by SINGHPRATAP** [comment]
I have also same problem. In my case heroku run bash is not working. It is showing ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000 . What should i do . Please help.

**Comment by alecarg** [comment]
For future reference: use add run*:detached* to your usual heroku run if your port 5000 is blocked.

**Comment by hugoh1995** [comment]
what if you need to access the console?

**Comment by dishani11** [comment]
I get same issue while trying " heroku run rake db:migrate". I am using windows 8.1

ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000

help me please!!

**Comment by umran23** [comment]
i got the same error in ubuntu linux 
when try to migrate database from rails to heroku 
ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000

**Comment by mauroprosperi** [comment]
got the same error, open the ports and reboot the system and now throws me another error :P

**Comment by edmorley** [comment]
These questions are unrelated to the original issue here - please open a support ticket instead if stuck :-)
