### ISSUE TITLE
ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000

### ISSUE THREAD

**Issue by SINGHPRATAP** [heroku/heroku-repo#59]

**Comment by SINGHPRATAP** [comment]
I am getting ETIMEDOUT: connect ETIMEDOUT 50.19.103.36:5000 when tring heroku run bash and same when trying heroku run rake db:migrate.

**Comment by sandeepsajan0** [comment]
It will  help  https://github.com/heroku/heroku-repo/issues/51
