### ISSUE TITLE
MODULE_NOT_FOUND: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by aleclarson** [heroku/heroku-repo#60]
Seems like `mkdirp` is missing from the `package.json`?

https://github.com/heroku/heroku-repo/blob/master/commands/clone.js#L8

**Comment by FDiskas** [comment]
still getting this error :heavy_division_sign:

**Comment by dmathieu** [comment]
@FDiskas ths package [is there](https://github.com/heroku/heroku-repo/blob/master/package.json#L14).
What is the full output of `heroku plugins`?

**Comment by FDiskas** [comment]
No plugins installed. Just wanted to deploy https://github.com/nfq-eta/react-typescript

**Comment by dmathieu** [comment]
If you have no plugin installed, you're not using this plugin then.
My recommendation would be to open a ticket on help.heroku.com.
