### ISSUE TITLE
WARNING: https://github.com/heroku/heroku-repo.git is a deprecated Ruby plugin

### ISSUE THREAD

**Issue by donnoman** [heroku/heroku-repo#63]
WARNING: https://github.com/heroku/heroku-repo.git is a deprecated Ruby plugin
WARNING: Check to see if there is a version of this plugin using the new Node.js Heroku CLI
...
 !    The Heroku Legacy Platform API will be Sunset on April 15th 2017. Please update your client access or the Heroku CLI to the latest version. See https://blog.heroku.com/sunsetting_heroku_s_legacy_platform_api_v2 for more details.

Will heroku-repo be updated?

**Comment by dmathieu** [comment]
Hey,

This repo has already been updated. You're probably running an old version.
You may want to try uninstalling it:

> heroku plugins:uninstall heroku-repo

And reinstalling it:

> heroku plugins:install heroku-repo

**Comment by donnoman** [comment]
Confirmed, all I had to do was `heroku plugins:install heroku-repo` and that resolved it. Sorry for the noise.
