### ISSUE TITLE
The Heroku Legacy Platform API will be Sunset on April 15th 2017

### ISSUE THREAD

**Issue by mkilling** [heroku/heroku-repo#67]
I received this warning today when I used `heroku repo:purge_cache`:

The Heroku Legacy Platform API will be Sunset on April 15th 2017. Please update your client access or the Heroku CLI to the latest version. See https://blog.heroku.com/sunsetting_heroku_s_legacy_platform_api_v2 for more details.

**Comment by dmathieu** [comment]
We fixed that here: 17bfe108c6d7016b451ddd7880be8103200108ff
Your CLI must not be up to date. Please do an `heroku update`.

**Comment by mkilling** [comment]
thanks, sorry!
