### ISSUE TITLE
Moving cache related commands to 'cache:*' rather than 'repo:*'

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-repo#69]
Currently the caching purging command is available as `heroku repo:purge_cache`. I believe this is since originally an app's cache was tied with the repo, however that's no longer the case.

As such, I think it makes sense to move the command to `heroku cache:purge` instead (with a deprecation period where the old command still works / warning message etc). This would also nicely tie in with adding some more cache related commands such as `cache:download` (which would mirror `slugs:download`).

If we do that, should we also move the cache commands to their own plugin - given the plugin name is unrelated? (With features like GitHub sync, I never touch the repo itself.) It just seems inconsistent to have the heroku-slugs command be separate, but repo and cache commands both in heroku-repo.

**Comment by tt** [comment]
I think a "cache" topic might be to ambiguous but it's also true that it doesn't really belong in this plug-in.

Consider it's a build concept, I would maybe move it to [the "heroku-builds" plug-in](https://github.com/heroku/heroku-builds). I'm not sure if the command should be `heroku builds:purge-cache` or `heroku builds:cache:purge` but I'm sure @heroku/cli has an opinion.

**Comment by dickeyxxx** [comment]
yeah I think you're right @tt, I mentioned this in this here: https://github.com/heroku/cli/pull/509

**Comment by edmorley** [comment]
That sounds even better - I've filed: heroku/heroku-builds#52

**Comment by edmorley** [comment]
Wontfix since this command has been moved to heroku-builds in heroku/heroku-builds#54, and is being deprecated in this plugin in #77.
