### ISSUE TITLE
applicatoin error

### ISSUE THREAD

**Issue by TELLO-TEL** [heroku/heroku-repo#71]
failed to connect monngodb to server

![screenshot 15](https://user-images.githubusercontent.com/21970290/28491052-5bbf293e-6ee9-11e7-9fb5-ac0d475f768f.png)

**Comment by TELLO-TEL** [comment]
im using mongolab and on localhost its working pefectly fine.but when deployed i getting an applicaton error and after checking the heroku logs im geting that error in that screenshot

**Comment by tt** [comment]
@TELLO-TEL, I'm sorry you're experiencing this problem. Can you please go to [help.heroku.com](https://help.heroku.com/) for a solution?

This repository is for issues with the heroku-repo CLI plug-in specifically.
