### ISSUE TITLE
reset command fails with parsing error when given an invalid app name

### ISSUE THREAD

**Issue by zeke** [heroku/heroku-repo#76]
👋 

I discovered this when accidentally specifying an app name that doesn't exist:

```
$ heroku repo:reset -a download-counts
Resetting Git repository for ⬢ download-counts... ⣯ 
 ▸    Unexpected token ! in JSON at position 1

$ heroku repo:reset -a npm-download-counts
Resetting Git repository for ⬢ npm-download-counts... done
```

**Comment by dmathieu** [comment]
@heroku/cli we're using [heroku.request](https://github.com/heroku/heroku-repo/blob/master/commands/reset.js#L7) to make that call, but it returns plain text.
What would be the way to avoid the response being parsed to json?

**Comment by jdxcode** [comment]
use `raw: true` I think
