### ISSUE TITLE
Certificate errors

### ISSUE THREAD

**Issue by coler-j** [heroku/heroku-repo#90]
Getting the follow error when trying to download the plugin (windows 10):

```
Installing heroku-repo@latest... !
 !    yarn add heroku-repo@latest --non-interactive --mutex=file:C:\Users\JLCJ\AppData\Local\heroku\plugins\yarn.lock
 !    --preferred-cache-folder=C:\Users\JLCJ\AppData\Local\heroku\yarn --registry=https://cli-npm.heroku.com exited with
 !    code 1
 !    error An unexpected error occurred: "https://cli-npm.heroku.com/heroku-repo: Hostname/IP does not match
 !    certificate's altnames: Host: cli-npm.heroku.com. is not in the cert's altnames: DNS:*.herokuapp.com,
 !    DNS:herokuapp.com".
 !
 !    yarn add v1.5.1
 !    info No lockfile found.
 !    [1/4] Resolving packages...
 !    info If you think this is a bug, please open a bug report with the information provided in
 !    "C:\\Users\\JLCJ\\AppData\\Local\\heroku\\plugins\\yarn-error.log".
 !    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 !
```

yarn-error.log contains:

```
Yarn version: 
  1.5.1

Node version: 
  9.10.1

Platform: 
  win32 x64

npm manifest: 
  {
    "private": true,
    "cli-engine": {
      "schema": 1
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: cli-npm.heroku.com. is not in the cert's altnames: DNS:*.herokuapp.com, DNS:herokuapp.com
      at Object.checkServerIdentity (tls.js:225:17)
      at TLSSocket.onConnectSecure (_tls_wrap.js:1056:27)
      at TLSSocket.emit (events.js:180:13)
      at TLSSocket._finishInit (_tls_wrap.js:633:8)

```

**Comment by OmarKhaledAbdo** [comment]
Having the same error on MacOs

**Comment by joaopedroasz** [comment]
Having the same error in my delpoy on heroku. I using Linux Mint 19.1 32bits

**Comment by kamransaeb** [comment]
Same on OSX

**Comment by astrofrog** [comment]
Getting this error too

**Comment by xjlin0** [comment]
same here

**Comment by alwyndavis** [comment]
Upgrading to the latest version (heroku/7.33.3 darwin-x64 node-v11.14.0 currently) fixed this issue for me.

Was previously on heroku-cli/6.16.12.

**Comment by callyb** [comment]
I'm getting this error now - but there's no ref to it apart from this one on stack/google/anywhere I can find...it's not heroku-cli because I'm not using it - I just uploaded my first react app to heroku a couple of days ago, it was working fine and now after a few seemingly benign updates to the code (mainly styling) it's showing this error and I've lost my app...

**Comment by dcporter44** [comment]
I'm also getting this error just trying to install a plugin "heroku plugins:install heroku-fork"

**Comment by tomaadland** [comment]
Updated to latest heroku-cli worked for me.

**Comment by superandrew** [comment]
`brew upgrade heroku` did the trick for me as well

**Comment by heaven** [comment]
Getting this:
```
heroku run rails c
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.heroku.com. is not in the cert's altnames: DNS:*.herokuapp.com, DNS:herokuapp.com
```

**Comment by nickramsbottom** [comment]
@heaven Heroku are reporting a problem with their API: https://status.heroku.com/

<img width="977" alt="image" src="https://user-images.githubusercontent.com/21983479/112504368-9d0c6700-8d83-11eb-9dfd-9820cdfd19fa.png">

Same error message brought me here.

**Comment by markdowney** [comment]
Heroku CLI is down: https://status.heroku.com/

**Comment by AmrSaber** [comment]
Same, I just got that same error now, it was working like 5 minutes ago

**Comment by savroff** [comment]
Admire with the word "Potential" in their statement

**Comment by heaven** [comment]
@nickramsbottom yep thanks, also just discovered this.

**Comment by supertrens** [comment]
And still down!

**Comment by gHashTag** [comment]
Waiting...

**Comment by Calamity-chain** [comment]
it seems to work again!

**Comment by emsuljic** [comment]
it works now

**Comment by edmorley** [comment]
Hi! The errors seen yesterday were due to:
https://status.heroku.com/incidents/2218

This GitHub issue was about something else (the error messages just happen to be similar) - likely using an out of date Heroku CLI.

If anyone else encounters the error in the original issue description, try uninstalling the Heroku CLI and reinstalling again:
https://devcenter.heroku.com/articles/heroku-cli#uninstalling-the-heroku-cli
https://devcenter.heroku.com/articles/heroku-cli#download-and-install

Closing to avoid confusion again in the future.
