### ISSUE TITLE
Failed to run repack

### ISSUE THREAD

**Issue by ramlaxmanyadav** [heroku/heroku-repo#91]
After running command `heroku repo:gc` getting 

fatal: unable to read a5b7cd1d601a1b29c1d6c23ed166ce7bd0454fe1
error: failed to run repack

**Comment by panozzaj** [comment]
Got the same error when running

**Comment by blarralde** [comment]
This has been happening to me for as long as we've had issues with slugs being to big, which is many years. Any people at heroku have any idea how to fix it?

**Comment by Dujota** [comment]
also running into this issue, our build succeeds and we don't seem to have any issue with the app in staging or production, but would be nice to resolve this error, since we've spent quite a bit of time looking into this "red herring"
